### PR TITLE
docs: use「hack」word

### PR DESCRIPTION
**Pull request by YeeJone**
There is no word「骇客」in Chinese..

### CODE REVIEW

**Comment by ai** [comment]
Can we rephrase to avoid English word?

cc @wenqiang @iDestin

**Comment by iDestin** [comment]
> Can we rephrase to avoid English word?
> 
> cc @wenqiang @iDestin

Of course, when I translated at that time, I thought hack was a word that everyone knew, and everyone could know the meaning of it when I used it directly, so I chose not to translate it. It may be a better choice to translate it into Chinese

**Comment by ai** [comment]
@iDestin can you send PR? I'm afraid to do it incorrectly because my eyes is not trained to operate with characters.

**Comment by ai** [comment]
Close for https://github.com/ai/nanoid/pull/386

**Pull request closed without merging**
