### PR TITLE
Reduce url.js size using genetic algorithm

### PR DESCRIPTION
**Pull request by polemius**
I have also written the [blog post](https://dev.to/polemius/how-i-reduce-the-size-of-library-with-genetic-algorithm-6m8) about this PR.

### CODE REVIEW

**Comment by ai** [comment]
Oh, wow! :D

1. Can you add Size Limit changes to the PR?
2. Can we remove `test/alphabet`? Or maybe we should rename `test/genetic-algorithm.js` to `test/alphabet`?
3. Can we reduce also other `*.browsser.js` files to see how method works in different files?

**Comment by polemius** [comment]
1. I've changed the size limit option for url.js. Did I miss something?
2. Yes, sure. I've changed it
3. I will run this algorithm with `index.browser.js` and we will see

**Comment by ai** [comment]
> I will run this algorithm with index.browser.js and we will see

Can you run it for `async/index.brower.js`, `random.browser.js` and `url.js`?

> Yes, sure. I've changed it

Hm, maybe I was wrong. Seems like the best strategy is to use old `test/alphabet` and then GA one. It will get the best result. Sorry for asking,  but can you revert `test/alphabet` removing (if I am right that they work better together).

**Comment by polemius** [comment]
I've reduced the size of `index.js` by 2 bytes 🎉  and `non-secure/index.js` by 1 byte. It is so cool!

**Comment by ai** [comment]
It’s really put Nano ID to next level of how much computer science can be used for the simple lib :D

**Comment by ai** [comment]
Released in 2.1.7.

I will post tweets during next week.

**Comment by polemius** [comment]
I've leaved this algorithm for all day and still no new results. I'm just thinking about changing also the variables in the code. Maybe the algorithm can find solution where total length of string will be higher but gziped size lower 🤔 
But again it was very fun and cool! Thank you for [this comment](https://github.com/ai/nanoid/pull/94#issuecomment-428763984). Because of it I made this PR :)

**Pull request merged**
