### PR TITLE
Browser: Generate random numbers in larger request sizes

### PR DESCRIPTION
**Pull request by pboyer**
Before
===
Screen Shot 2020-10-26 at 10 16 55 AM

After
===
Screen Shot 2020-10-26 at 10 23 02 AM

### CODE REVIEW

**Comment by ai** [comment]
CI is falling (very likely because of bundle size increasing)

**Comment by ai** [comment]
Sometimes we have an Jest coverage issue. Call `npm test` kindly multiple times or call `npx size-limit` directly.

**Comment by pboyer** [comment]
Thanks for taking a look @ai.

I updated the size limits.

I can confirm that the `jest-ci --coverage` call is flaky. Here's what I see locally:

```peter@Peters-MacBook-Pro nanoid % npm run test

> nanoid@3.1.16 test /Users/peter/git/nanoid
> jest-ci --coverage && eslint-ci . && check-dts && size-limit && yarn spell

 PASS  bin/nanoid.test.js
 PASS  test/old-browser.test.js
 PASS  test/ie.test.js
 PASS  test/react-native-polyfill.test.js
 PASS  test/react-native.test.js
 PASS  test/non-secure.test.js (5.885 s)
 PASS  test/async.test.js (9.364 s)
 PASS  test/index.test.js (10.017 s)
---------------------|---------|----------|---------|---------|-------------------
File                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
---------------------|---------|----------|---------|---------|-------------------
All files            |     100 |    98.33 |     100 |     100 |                   
 nanoid              |     100 |    97.56 |     100 |     100 |                   
  index.browser.js   |     100 |    96.67 |     100 |     100 | 6                 
  index.js           |     100 |      100 |     100 |     100 |                   
 nanoid/async        |     100 |      100 |     100 |     100 |                   
  index.browser.js   |     100 |      100 |     100 |     100 |                   
  index.js           |     100 |      100 |     100 |     100 |                   
 nanoid/non-secure   |     100 |      100 |     100 |     100 |                   
  index.js           |     100 |      100 |     100 |     100 |                   
 nanoid/url-alphabet |     100 |      100 |     100 |     100 |                   
  index.js           |     100 |      100 |     100 |     100 |                   
---------------------|---------|----------|---------|---------|-------------------

Test Suites: 8 passed, 8 total
Tests:       53 passed, 53 total
Snapshots:   0 total
Time:        10.41 s, estimated 11 s
Ran all test suites.
Prettier: Clearing config cache ...
✔ Check types
✔ Compiling files to ESM
✔ Adding to empty webpack project
  
  nanoid
  Size limit: 192 B
  Size:       168 B with all dependencies, minified and gzipped
  
  customAlphabet
  Size limit: 192 B
  Size:       192 B with all dependencies, minified and gzipped
  
  urlAlphabet
  Size limit: 59 B
  Size:       59 B with all dependencies, minified and gzipped
  
  non-secure nanoid
  Size limit: 103 B
  Size:       103 B with all dependencies, minified and gzipped
  
  non-secure customAlphabet
  Size limit: 45 B
  Size:       45 B with all dependencies, minified and gzipped
  
  async nanoid
  Size limit: 118 B
  Size:       118 B with all dependencies, minified and gzipped
  
  async customAlphabet
  Size limit: 138 B
  Size:       138 B with all dependencies, minified and gzipped
  
yarn run v1.22.4
$ yaspeller-ci *.md
Spelling check:
✓ /Users/peter/git/nanoid/CHANGELOG.md 2170 ms
✓ /Users/peter/git/nanoid/README.md 694 ms
No errors.
Checking finished: 3.051 sec.
✨  Done in 3.36s.
peter@Peters-MacBook-Pro nanoid % npm run test

> nanoid@3.1.16 test /Users/peter/git/nanoid
> jest-ci --coverage && eslint-ci . && check-dts && size-limit && yarn spell

 PASS  test/react-native-polyfill.test.js
 PASS  test/react-native.test.js
 PASS  test/ie.test.js
 PASS  test/old-browser.test.js
 PASS  bin/nanoid.test.js
 PASS  test/non-secure.test.js (5.403 s)
 PASS  test/async.test.js (8.8 s)
 PASS  test/index.test.js (9.545 s)
---------------------|---------|----------|---------|---------|-------------------
File                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
---------------------|---------|----------|---------|---------|-------------------
All files            |   99.36 |    98.33 |     100 |   99.33 |                   
 nanoid              |     100 |    97.56 |     100 |     100 |                   
  index.browser.js   |     100 |    96.67 |     100 |     100 | 6                 
  index.js           |     100 |      100 |     100 |     100 |                   
 nanoid/async        |   98.21 |      100 |     100 |   98.11 |                   
  index.browser.js   |     100 |      100 |     100 |     100 |                   
  index.js           |   96.43 |      100 |     100 |   96.15 | 51                
 nanoid/non-secure   |     100 |      100 |     100 |     100 |                   
  index.js           |     100 |      100 |     100 |     100 |                   
 nanoid/url-alphabet |     100 |      100 |     100 |     100 |                   
  index.js           |     100 |      100 |     100 |     100 |                   
---------------------|---------|----------|---------|---------|-------------------
Jest: "global" coverage threshold for statements (100%) not met: 99.36%

Test Suites: 8 passed, 8 total
Tests:       53 passed, 53 total
Snapshots:   0 total
Time:        9.922 s, estimated 11 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nanoid@3.1.16 test: `jest-ci --coverage && eslint-ci . && check-dts && size-limit && yarn spell`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nanoid@3.1.16 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/peter/.npm/_logs/2020-10-26T19_27_59_564Z-debug.log
```

Two tests. One fails, one succeeds with no change in the code.

**Comment by ai** [comment]
@pboyer 2x size increasing is a lot. It do not worth calculation performance.

**Comment by ai** [comment]
We need a good calling performance on Node.js, where we have servers which process many users.

On client-side we have rare Nano ID calls.

**Comment by pboyer** [comment]
That's fair. I made a best effort attempt to make this PR smaller, but could only shave off a few bytes. 

I would argue that 192/108B => 78% larger for a 3-4x performance improvement is worth it, but I'm not the maintainer. :) This library would be about 1/2 the size of uuid _and_ more performant than uuid/v4 in all environments (today it is ~4x slower than uuid/v4 in browser).

**Comment by ai** [comment]
Yeap, it is always hard to choose what to optimize.

Nano ID was started as an art project to promote the idea of JS size optimization for libraries. So size optimization is a key thing for the project.

**Pull request closed without merging**
