### PR TITLE
simplifies code contributions by fully automating the setup with gitpod

### PR DESCRIPTION
**Pull request by nisarhassan12**
Hi! :slightly_smiling_face:

This Pr simplifies code contributions by fully automating the setup with gitpod (A free online vs code like ide) with a single click it will launch a ready to code workspace with all the dependencies pre-installed and the web server running so that anyone interested in contributing can start straight away without wasting time on the setup.

It seems to work well :) You can give it a try on my fork via the link below:

https://gitpod.io/#https://github.com/nisarhassan12/nanoid/

image

### CODE REVIEW

**Comment by ai** [comment]
1. We need to fix docs. At least be more accurate with capitalization (`ide` > `IDE`)
2. Right now we allow to work only with `index.browser.js`, which is small part of the project. To convince me you need to show how to work with all different use cases: async, Node’s `index.js`, maybe even have see interactive benchmark result

**Comment by nisarhassan12** [comment]
Thanks! @ai I have changed the capitalization. 
interactive benchmark and size-limit result:
image
Async:
image

**Comment by ai** [comment]
Does this benchmark and async tests work directly in gitpod?

**Comment by nisarhassan12** [comment]
> Does this benchmark and async tests work directly in gitpod?

Yes! Gitpod is a full-featured dev environment based on Docker. It uses Ubuntu Linux under the hood. You can run the benchmark, tests and another node stuff directly in gitpod by opening a terminal tab.

**Comment by ai** [comment]
Do we need a config if we need to run tests, size-limit and benchmark?

We do not need to run web server.

**Comment by nisarhassan12** [comment]
> Do we need a config if we need to run tests, size-limit and benchmark?

We don't need a config if we want to run tests, size-limit and benchmark all of these can be run manually by opening a terminal tab but if we want to automate any of these when the workspace start we can do that via the `.gitpod.yml` config file.

**Comment by ai** [comment]
1. Let’s remove `yarn start` because this web server is not important compared to tests and size-limit
2. I do not like the idea to add another config just to open web IDE (there are a lot of projects like this, I do not want to support only one of them). But I like the idea of one-click workspace: click the link and got opened `index.browser.js` with the test and `size-limit` live results. It will be cool and definitely worth extra config.
3. Can we add config to `package.json`? If not, you need to add config to `.npmignore`.

**Comment by nisarhassan12** [comment]
Thanks! I have made the changes. This is how it looks now:

image

**Comment by ai** [comment]
Can you replace benchmark with `size-limit`? It is main metric for optimization here.

**Comment by nisarhassan12** [comment]
> Can you replace a benchmark with `size-limit`? It is the main metric for optimization here.
> 
> We may need some watch script to re-run `size-limit` on `*.js` files changes.

I have replaced the benchmark with size-limit and size limit re-runs agains whenever there is change. This is how it looks now: 
image

**Comment by ai** [comment]
1. Looks great. Last thing: seems like this `watch` script removes all colors. Do we have an alternative for watching?
2. Do you have a Twitter account to mention you on my Twitter for this work when we will finish it?

**Comment by nisarhassan12** [comment]
> 1. Looks great. Last thing: seems like this `watch` script removes all colors. Do we have an alternative for watching?
>
> 2. Do you have a Twitter account to mention you on my Twitter for this work when we will finish it?

Thanks! I have made the changes this is how it looks now the coloring is back :slightly_smiling_face:  
My Twiiter Account: https://twitter.com/nisarhassan12

image

**Comment by ai** [comment]
Looks great. Sorry, I am on travel and can’t accept it today.

**Comment by nisarhassan12** [comment]
> Looks great. Sorry, I am on travel and can’t accept it today.

No! Problem! Thanks

**Pull request merged**
