### PR TITLE
Shave 3 bytes in generate & async/generate again

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by ai** [comment]
Can you update `size-limit` in `package.json` to have nice PR for Twitter?

**Comment by MaxGraey** [comment]
sure

**Comment by MaxGraey** [comment]
Benchmark. To make sure all stay relatively the same

* origin/master
```
nanoid                    381,404 ops/sec
nanoid/generate           384,872 ops/sec
uid.sync                  294,232 ops/sec
uuid/v4                   318,900 ops/sec
secure-random-string      277,231 ops/sec
shortid                    35,320 ops/sec

Async:
nanoid/async               60,292 ops/sec
nanoid/async/generate      59,263 ops/sec
secure-random-string       57,555 ops/sec
uid                        56,355 ops/sec

Non-secure:
nanoid/non-secure       2,144,577 ops/sec
rndm                    1,965,030 ops/sec
```

* origin/minor-improcments
```
nanoid                    376,130 ops/sec
nanoid/generate           377,930 ops/sec
uid.sync                  292,587 ops/sec
uuid/v4                   322,464 ops/sec
secure-random-string      278,277 ops/sec
shortid                    35,779 ops/sec

Async:
nanoid/async               61,254 ops/sec
nanoid/async/generate      59,677 ops/sec
secure-random-string       55,500 ops/sec
uid                        55,630 ops/sec

Non-secure:
nanoid/non-secure       2,114,608 ops/sec
rndm                    1,959,539 ops/sec
```

**Comment by ai** [comment]
Thanks. Amazing results =^_^=

**Pull request merged**
