### PR TITLE
Reduced size by few bytes 👾

### PR DESCRIPTION
**Pull request by rqrqrqrq**
Some gzip stuff similar to @subzey's pr.

### CODE REVIEW

**Comment by ai** [comment]
Wow 😍

**Comment by ai** [comment]
Do you have Twitter to mention you?

**Comment by ai** [comment]
Released in 1.2.6

**Comment by rqrqrqrq** [comment]
@ai sure, https://twitter.com/rqtdfh

**Comment by ai** [comment]
BTW, maybe we should create a tool to bruteforce alphabet order? https://cultofmartians.com/tasks/nanoid-brute.html

**Pull request merged**
