### PR TITLE
Add process definition check

### PR DESCRIPTION
**Pull request by guybedford**
Fix as per https://github.com/ai/nanoid/issues/237, pending further testing.

### CODE REVIEW

**Comment by ai** [comment]
Adding `typeof process` force webpack to add a huge `process` polyfill and bloat the library size 7x times.

Try `"process" in this` or some similar hack.

**Comment by TrySound** [comment]
Please see my comment
https://github.com/ai/nanoid/issues/237#issuecomment-702338527

**Comment by guybedford** [comment]
Hmm actually I don't think there's a way to accomplish this if the constraint is Webpack support!

@ai note that `this` is not the global in native ES modules, it is instead `.undefined`

@TrySound that's fine but assumes that all ES modules should run through a build system to execute in an environment that is not Node.js. We shouldn't have to enforce this restriction on the JS ecosystem, and that's an important thing to avoid lock-in to tooling silos over native workflows which should define the base-level semantics. The tail is wagging the dog currently!

Posted https://github.com/webpack/webpack/issues/11569.

**Comment by ai** [comment]
@guybedford maybe we need to create an issue in jspm? `process.env.NODE_ENV` is a popular way.

With `typeof process` we do not solve the problem. jspm build still contains unnecessary code for production (we just disable it, but still send it to client).

**Comment by guybedford** [comment]
@ai the modern way to do this branching is with the `"exports"` field:

```json
{
  "exports": {
    "production": "./production-index.js",
    "development": "./development-index.js"
  }
}
```

and jspm supports this.

By assuming a build tool will inline `process.env.NODE_ENV` for a native ES module, that means that the "browser" export defined here is not really a browser file at all - but rather a module that is expected to run through a bundler. It is that expectation which continues to create a reliance on overly complex build tools for beginners to use the web platform, when modules should be able to execute in browser directly with just a local server and an import map, which is a key use case jspm is designed to enable and not restrict. Tools should be designed to set users free of them.

**Comment by ai** [comment]
@guybedford we can add `exports.production: 'index.production.js'` and put a copy of `index.browser.js` without a development code

**Comment by guybedford** [comment]
@ai the problem with that is that even then, jspm will use the "development" branch on jspm.dev which will still break!

I'd suggest shipping CommonJS for this file if assuming the process global, and then later on switching to "development" / "production" exports once those have wider support in tooling.

**Pull request closed without merging**
