### PR TITLE
Reduce url symbols size for 3 bytes

### PR DESCRIPTION
**Pull request by philosaf**
Some symbols movement for improving gzip size from 73 bytes to 70 (checked with size-limit)

### CODE REVIEW

**Comment by ai** [comment]
😄 sure. Let's just explain alphabet and trick in the comment.

Compare to `index.js` tricks are less expected here.

**Comment by ai** [comment]
Also, maybe you want to implement this task, to be sure that it is the best alphabet order

https://cultofmartians.com/tasks/nanoid-brute.html

**Comment by ai** [comment]
Yeap, I know how it works.

But when users will try to find what alphabet is used in Nano ID, user will be confused about `url.js` content. This is why we need to explain it in commend in the code (like “this alphabet uses `a-zA-Z0-9_~`, we changed symbols order for better gzip compression”).

**Comment by philosaf** [comment]
Done.
Did not have time to fix `yaspeller` errors :smile:

**Comment by ai** [comment]
Released in 1.3

**Pull request merged**
