### PR TITLE
Adding example for react using hooks

### PR DESCRIPTION
**Pull request by nahumzs**
This helps to understand how to use nanoid with react hooks.

### CODE REVIEW

**Comment by ai** [comment]
Am I right, that `nanoid()` will be called on every component render? I could be bad for performance.

What do you think aboiut this way to use Nano ID with hooks?

```
const key = useMemo(nanoid)
```

**Comment by TrySound** [comment]
@ai in this case nanoid is called on every render too unless you specify dependencies list. And still useMemo is not stable. It works only for pure computations. React may drop cache any time. These are ways to go.

```js
const useNanoid = () => {
  const ref = React.useRef(null)
  if (ref.current == null) {
    ref.current = nanoid();
  }
  return ref.current;
}

const Component = () => {
  const id = useNanoid()
}
```

```js
const Component = () => {
  const [id] = React.useState(() => nanoid());
}
```

**Comment by nahumzs** [comment]
I put a small example on place https://codesandbox.io/s/nanoid-with-hooks-yv1u5 ref

**Comment by TrySound** [comment]
Did you save it? I don't see any nanoid usage.

**Comment by nahumzs** [comment]
@TrySound sorry my bad is there now.

**Comment by ai** [comment]
@nahumzs OK, seems like `useMemo` doesn't work. What do you think about `const [id] = useState(nanoid)`?

**Comment by TrySound** [comment]
`useMemo(() => nanoid(), [])` does work but eventually may break because nanoid is not pure computation.

**Comment by nahumzs** [comment]
`const idState = React.useState(() => nanoid())` this will work as well and is a smoother syntax than ref (I updated the example)

**Comment by ai** [comment]
ref has a problem with calling Nano ID on every component render. It didn't change the ID, but use CPU.

**Comment by ai** [comment]
Thanks for improving docs :)

**Pull request merged**
