### PR TITLE
chore: add missing size-limit dependency

### PR DESCRIPTION
**Pull request by CyberAP**

### CODE REVIEW

**Comment by ai** [comment]
`@size-limit/preset-small-lib` already installs `size-limit`. Do you have some problem with this method?

**Comment by CyberAP** [comment]
Yes, when running `npm run test` I get an error that size-limit is an unkown command.

**Comment by ai** [comment]
We do not have such problem on Travis CI. Is it Windows specific problem?

Can you try to replace `size-limit` in `scripts` to.`npx size-limit`?

**Comment by CyberAP** [comment]
I think I had a corrupt package-lock.json. Making a clean install fixed the issue. Sorry for the inconvenience.

**Pull request closed without merging**
