### PR TITLE
Speedup mask calculation in format

### PR DESCRIPTION
**Pull request by MaxGraey**
- replace emulated integer `log2(x)` to `31 - clz(x)` which should speed up bust formatting
- move `size = +size` before it first usage

Coveats: **+2 bytes**

### CODE REVIEW

**Comment by ai** [comment]
1. Can you increase Size Limit in the config? `package.json` → `size-limit`. It will make PR green.
2. Can you show `test/benchmark` result before and after changes?

**Comment by MaxGraey** [comment]
1. Done
2. I'm not sure how I could do this. Lib don't have built-in benchmark suite.

**Comment by ai** [comment]
2. `git checkout master; ./test/benchmark; git checkout improve-format; ./test/benchmark` should compare master and your branch

**Comment by MaxGraey** [comment]
Ok, thanks!
- origin/master

```
nanoid                    399,461 ops/sec
nanoid/generate           380,342 ops/sec
uid.sync                  316,353 ops/sec
uuid/v4                   343,762 ops/sec
secure-random-string      297,783 ops/sec
shortid                    40,058 ops/sec

Async:
nanoid/async               62,342 ops/sec
nanoid/async/generate      61,241 ops/sec
secure-random-string       58,221 ops/sec
uid                        56,237 ops/sec

Non-secure:
nanoid/non-secure       2,123,242 ops/sec
rndm                    1,945,954 ops/sec
```

- improve-format

```
nanoid                    394,783 ops/sec
nanoid/generate           386,858 ops/sec
uid.sync                  314,557 ops/sec
uuid/v4                   339,485 ops/sec
secure-random-string      299,192 ops/sec
shortid                    40,247 ops/sec

Async:
nanoid/async               60,308 ops/sec
nanoid/async/generate      59,430 ops/sec
secure-random-string       57,150 ops/sec
uid                        53,721 ops/sec

Non-secure:
nanoid/non-secure       2,130,307 ops/sec
rndm                    1,960,769 ops/sec

```

**Comment by ai** [comment]
Released in 2.1.4

**Comment by ai** [comment]
We still support IE. I am reverting the changes until Nano ID 3.

**Comment by MaxGraey** [comment]
Hmm, didn't know about this. In that's case better use old approach instead polyfilling

**Pull request merged**
