### PR TITLE
Stabilize tests in async/index.js

### LINKED ISSUE #283: Stabilize tests
`jest --coverage` depends on random and sometimes ignores 50 line in `async/index.js`

Example: https://github.com/ai/nanoid/runs/2749571294?check_suite_focus=true

### PR DESCRIPTION
**Pull request by immitsu**
Fix #283

### CODE REVIEW

**Comment by ai** [comment]
Can I ask you to run `./test/benchmark` before and after these changes?

**Comment by immitsu** [comment]
Sure.
I've run both versions five times, and the old `async customAlphabet`, on average, is a little bit faster - 69.1 against 68.5

**Comment by ai** [comment]
New change will not work. We do not know how many random bytes we will need (because we are ignoring done sets). This is why we have `while (true)`.

**Comment by ai** [comment]
Performance drop is not a good thing. Especially because we can fix this issue by fixing the test, not the code

**Comment by ai** [comment]
The problem was fixed with `crypto` mock https://github.com/ai/nanoid/pull/285

**Pull request closed without merging**
