### PR TITLE
Add flow types definitions

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by ai** [comment]
Can Flow use TypeScript type definitions? I don’t want to make npm package bigger by putting type definitions for every language :).

**Comment by TrySound** [comment]
@ai Sadly no. And I don't think you need to choose. As you don't use type checkers accept both or send us to typings repositories.

**Comment by ai** [comment]
Typings repositories sounds like good idea :) In this case only Flow/TS users will download type definitions

**Comment by TrySound** [comment]
Yep

**Pull request closed without merging**
