### PR TITLE
Fix: secure-random-number-generator not found in RN debug mode.

### PR DESCRIPTION
**Pull request by skaldo**
https://github.com/ai/nanoid/issues/162

### CODE REVIEW

**Comment by ai** [comment]
In this PR you force RN to use Node.js version. Node.js version use `crypto` Node.js module.

Is this module now available in RN?

**Comment by skaldo** [comment]
RN uses the `index.js` that then imports `./random.rn.js` as specified in package.json for RN environment.
`random.rn.js` does use `expo-random` and not the `crypto` module.

**Comment by ai** [comment]
@skaldo Yeap, we did it because RN doesn't support `crypto`.

Did it got `crypto` support recently?

**Comment by skaldo** [comment]
Your implementation in `random.rn.js` is pretty correct. Just the path how to get to this file is not.

> RN uses the index.js that then imports ./random.rn.js as specified in package.json for RN environment.

Here I mean my PR. What happens without my changes in debug mode is: `index.browser.js` gets executed and an exception is thrown (not taking in account the presence of `expo-random` in the project).

I also corrected the test, as `index.browser.js` is now not executed in the react-native context.

**Comment by ai** [comment]
Sorry, I have a lack of RN experience and need more details to change RN behavior (and my answers is not quick, because of vacation).

> index.browser.js gets executed and an exception is thrown (not taking in account the presence of expo-random in the project).

Did I understand correctly, that you load `nanoid` in your RN project, but in debug mode (which works in Chrome) you do not need to use `expo-random`?

But wy do you import `nanoid` and not `nanoid/async`?

**Comment by skaldo** [comment]
No worries! We do have a patch in our repo so this is not that urgent.

Actually your last sentence brought me to the point - I checked the stack trace again and saw `browserLoginFlow.js`. Searching through dependencies I found an internal dependency that is importing `nanoid` and not `nanoid/async`. This explains the mystery how at all `index.browser.js` gets executed.

Why this is not working in debug mode? Checking the code of our dependency reveals following:
```
var crypto = window.crypto || window.msCrypto;
var nanoid = crypto ? require('nanoid') : require('nanoid/non-secure'); 
```
If crypto is available (RN in debug mode), `nanoid` is required -> `index.browser.js` is executed and exception is thrown. In the other case, `nanoid/non-secure` is used.

Seeing all of this, I do not think that you need my PR as this should not happen to a regular user of this library. I would maybe just make the error more explicit. Something like this:
`
You should not import nanoid directly in React Native. If you don't need unpredictable IDs, you should use either nanoid/non-secure or install expo-random and use nanoid/async.
`

If you want, I can update my PR. In the other case, you can just close it.

**Comment by ai** [comment]
It is always a good feeling when you find a reason.

Do you have any idea how we can improve error message to help future developers to find a problem?

**Comment by swernerx** [comment]
Interesting that this came up again. See my last PR which was closed because nobody in our team had time to check: https://github.com/ai/nanoid/pull/136

**Pull request closed without merging**
