### PR TITLE
fix: avoid require bug in node.js 13.0

### PR DESCRIPTION
**Pull request by bluelovers**
https://github.com/nodejs/modules/issues/446

    "Error: Package exports for '/data/data/com.termux/files/home/.config/yarn/global/node_modules/nanoid' do not define a valid '.' target\n"

Screenshot_20200412-121017_Termux

### CODE REVIEW

**Comment by ai** [comment]
@bluelovers [`dual-publish`](https://github.com/ai/dual-publish/) automatically [inserts](https://github.com/ai/dual-publish/blob/master/process-dir.js#L131) `main` to `package.json` during the publish.

How I can reproduce your issue?

**Comment by bluelovers** [comment]
this pr is failed, it can't fix this issue

but if i edit inretface-datastore/src/key.js

replace `nanoid` to `nanoid/index` will not have this error at start up
but i can't replace it at every where

---


install termux on android phone
install git and nodejs , yarn
nodejs will be 13.0.0 <== new version didn't have this issue, but termux only have this version

```bash
yarn global add novel-opds-now
novel-opds-now
```

don't use npm install this
will see this error



---

i also try request termux update nodejs too, but not sure they will see my email xd

**Comment by ai** [comment]
It happens because Node.js 13 does not support conditional exports. Look at `node_modules/nanoid/package.json`.

You can enable it manually by running `node --experimental-conditional-exports`.

**Comment by TrySound** [comment]
@ai But it does support. Just emits warning.

**Comment by ai** [comment]
@TrySound there were some bugs in old Node.js 13.0 versions.

I think we should support only the latest version of each Node.js 10.x, 12.x, and 13.x branches.

**Pull request closed without merging**
